#PBS -N interf_419_95
#PBS -l walltime=20:00:00
#PBS -l nodes=1:ppn=1
#PBS -A PAS0174
#PBS -l mem=20GB
#PBS -j oe
cd $PBS_O_WORKDIR
source ../env.sh
cp runInterferometry $TMPDIR
cd $TMPDIR    

##./runInterferometry -PB -O/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter/run419 -S100 -s95 419

## for data
./runInterferometry -Noverlap -PB --FILTER_OPTION=4 -bbaselineSampleSmooth_1_2.00.root -O/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter/run419 -S100 -s95 419


## for Sim
##./runInterferometry -PB -u -bbaselineSampleSmooth_1_2.00.root -O/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter/run419 -S100 -s95 419


###for i in {175..439};
##for i in {175..175};
##do

##  ./runInterferometry -PB -O/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter/run419 -S100 -s95 419

##done

