#PBS -N stage02_sim_v
#PBS -l walltime=6:00:00
#PBS -l nodes=1:ppn=1 
#PBS -l mem=10GB
#PBS -j oe
#PBS -A PAS0174
cd $PBS_O_WORKDIR
##cp runAnalysisStage02 $TMPDIR
##cd $TMPDIR    
source ../env.sh


##./runAnalysisStage02 -D../results -I/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter 175 439 -PV -S_v -u -F../analysisSoftware/results/plots/analysisOutput_801_808.root

##./runAnalysisStage02 -D../results -I/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter 175 439 -PH -S_h_side -FanalysisOutput90/anlysisOutput_175_439_0.root 

##./runAnalysisStage02 -D../results -I/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter 175 439

##cp runAnalysisStage02.out $PBS_O_WORKDIR

./runAnalysisStage02 -D../resultsNewSim -I/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter 1 500 -PV -S_v -u -B -A -FanalysisOutput_1_500_0.root

##./runAnalysisStage02 -D../resultsAltCuts/noSatNoTrigDir -I/fs/scratch/PAS0174/anita/2015_05_19/sample_90/geomFilter 1 500 -PV -S_v -u -B -A -FanalysisOutput_1_500_0.root

